const email = [
  { id: "em-hibp", label: "HaveIBeenPwned", tag: "Search", status: "active", inputs: ["email"], url: (e) => `https://haveibeenpwned.com/account/${encodeURIComponent(e)}` },
  { id: "em-dehashed", label: "Dehashed Email Check", tag: "Search", status: "active", inputs: ["email"], url: (e) => `https://dehashed.com/search?query=%22${encodeURIComponent(e)}%22` },
  { id: "em-spycloud", label: "Spycloud Stats", tag: "Search", status: "active", inputs: ["email"], url: (e) => `https://portal.spycloud.com/endpoint/enriched-stats/${encodeURIComponent(e)}` },
  { id: "em-hudsonrock", label: "HudsonRock Preview", tag: "Search", status: "active", inputs: ["email"], url: (e) => `https://cavalier.hudsonrock.com/api/json/v2/preview/search-by-login/osint-tools?email=${encodeURIComponent(e)}` },
  { id: "em-cybernews", label: "Cybernews Check", tag: "Search", status: "active", inputs: ["email"], url: (e) => `https://check.cybernews.com/chk/?lang=en_US&e=${encodeURIComponent(e)}` },
  { id: "em-psbdmp", label: "PSBDMP Search", tag: "Search", status: "active", inputs: ["email"], url: (e) => `https://psbdmp.ws/api/search/${encodeURIComponent(e)}` },
  { id: "em-intelx", label: "Intelligence X Search", tag: "Search", status: "active", inputs: ["email"], url: (e) => `https://intelx.io/?s=${encodeURIComponent(e)}` },
  { id: "em-cleantalk", label: "CleanTalk Email Check", tag: "Search", status: "active", inputs: ["email"], url: (e) => `https://cleantalk.org/email-checker/${encodeURIComponent(e)}` },
  { id: "em-leakix", label: "LeakIX Scope Leak", tag: "Search", status: "active", inputs: ["email"], url: (e) => `https://leakix.net/search?scope=leak&q=%22${encodeURIComponent(e)}%22` },
  { id: "em-hunterverify", label: "Hunter Email Verifier", tag: "Search", status: "active", inputs: ["email"], url: (e) => `https://hunter.io/email-verifier/${encodeURIComponent(e)}` },
  { id: "em-occrp", label: "OCCRP Public Database", tag: "Search", status: "active", inputs: ["email"], url: (e) => `https://data.occrp.org/search?q=${encodeURIComponent(e)}` },
  { id: "em-spytox", label: "SpyTox Search", tag: "Search", status: "active", inputs: ["email"], url: (e) => `https://www.spytox.com/people/search?email=${encodeURIComponent(e)}` },
  { id: "em-thatsthem", label: "ThatsThem Email Check", tag: "Search", status: "active", inputs: ["email"], url: (e) => `https://thatsthem.com/email/${encodeURIComponent(e)}` },
  { id: "em-truepeople", label: "TruePeopleSearch Email", tag: "Search", status: "active", inputs: ["email"], url: (e) => `https://www.truepeoplesearch.com/resultemail?email=${encodeURIComponent(e)}` },
  { id: "em-proton", label: "ProtonMail PGP Lookup", tag: "Search", status: "active", inputs: ["email"], url: (e) => `https://api.protonmail.ch/pks/lookup?op=get&search=${encodeURIComponent(e)}` },
  { id: "em-whoisology", label: "Whoisology Reverse Email", tag: "Search", status: "active", inputs: ["email"], url: (e) => `https://whoisology.com/email/${encodeURIComponent(e)}` },
  { id: "em-analyzeid", label: "AnalyzeID Reverse Email", tag: "Search", status: "active", inputs: ["email"], url: (e) => `http://analyzeid.com/?email=${encodeURIComponent(e)}` },
  { id: "em-whoxy", label: "Whoxy Reverse Email", tag: "Search", status: "active", inputs: ["email"], url: (e) => `https://www.whoxy.com/search.php?email=${encodeURIComponent(e)}` },
  { id: "em-scamsearch", label: "ScamSearch", tag: "Search", status: "active", inputs: ["email"], url: (e) => `https://scamsearch.io/search_report?searchoption=all&search=${encodeURIComponent(e)}` },
  { id: "em-skymem", label: "SkyMem Search", tag: "Search", status: "active", inputs: ["email"], url: (e) => `https://www.skymem.info/srch?q=${encodeURIComponent(e)}` },
  { id: "em-flickr", label: "Flickr People Search", tag: "Search", status: "active", inputs: ["email"], url: (e) => `https://www.flickr.com/search/people/?q=${encodeURIComponent(e)}` },
  { id: "em-emailrep", label: "EmailRep.io Reputation", tag: "Search", status: "active", inputs: ["email"], url: (e) => `https://emailrep.io/query/${encodeURIComponent(e)}` },
  { id: "em-gravatar", label: "Gravatar Profile Check", tag: "Search", status: "active", inputs: ["email"], url: (e) => `https://en.gravatar.com/site/check/${encodeURIComponent(e)}` },
  { id: "em-google-dork", label: "Google Email Dork", tag: "Search", status: "active", inputs: ["email"], url: (e) => `http://google.com/search?q=%22${encodeURIComponent(e)}%22` },
  { id: "em-bing-dork", label: "Bing Email Dork", tag: "Search", status: "active", inputs: ["email"], url: (e) => `http://bing.com/search?q=%22${encodeURIComponent(e)}%22` },
  { id: "em-yandex-dork", label: "Yandex Email Dork", tag: "Search", status: "active", inputs: ["email"], url: (e) => `https://yandex.com/search/?text=%22${encodeURIComponent(e)}%22` },
];

export default email;
