const engines = [
  { id: "eg-google", label: "Google", tag: "Search", status: "active", inputs: ["query"], url: (q) => `http://google.com/search?q=${encodeURIComponent(q)}` },
  { id: "eg-google-date", label: "Google Date Range", tag: "Search", status: "active", inputs: ["query"], url: (q) => `http://google.com/search?q=${encodeURIComponent(q)}&tbs=cdr:1,cd_min:1/1/0,sbd:1` },
  { id: "eg-google-news", label: "Google News", tag: "Search", status: "active", inputs: ["query"], url: (q) => `http://www.google.com/search?tbm=nws&q=${encodeURIComponent(q)}` },
  { id: "eg-google-ftp", label: "Google FTP Search", tag: "Search", status: "active", inputs: ["query"], url: (q) => `https://www.google.com/search?q=inurl%3Aftp%20-inurl%3A(http|https)%20${encodeURIComponent(q)}` },
  { id: "eg-google-index", label: "Google Index Dork", tag: "Search", status: "active", inputs: ["query"], url: (q) => `https://www.google.com/search?q=intitle%3Aindex.of+${encodeURIComponent(q)}` },
  { id: "eg-google-scholar", label: "Google Scholar", tag: "Search", status: "active", inputs: ["query"], url: (q) => `http://scholar.google.com/scholar?&q=${encodeURIComponent(q)}` },
  { id: "eg-google-patents", label: "Google Patents", tag: "Search", status: "active", inputs: ["query"], url: (q) => `https://patents.google.com/?q=${encodeURIComponent(q)}` },
  { id: "eg-bing", label: "Bing", tag: "Search", status: "active", inputs: ["query"], url: (q) => `http://bing.com/search?q=${encodeURIComponent(q)}` },
  { id: "eg-bing-news", label: "Bing News", tag: "Search", status: "active", inputs: ["query"], url: (q) => `http://bing.com/news/search?q=${encodeURIComponent(q)}` },
  { id: "eg-yahoo", label: "Yahoo", tag: "Search", status: "active", inputs: ["query"], url: (q) => `http://search.yahoo.com/search?p=${encodeURIComponent(q)}` },
  { id: "eg-yandex", label: "Yandex", tag: "Search", status: "active", inputs: ["query"], url: (q) => `http://www.yandex.com/yandsearch?text=${encodeURIComponent(q)}` },
  { id: "eg-baidu", label: "Baidu", tag: "Search", status: "active", inputs: ["query"], url: (q) => `http://baidu.com/s?wd=${encodeURIComponent(q)}` },
  { id: "eg-searx", label: "Searx Meta Search", tag: "Search", status: "active", inputs: ["query"], url: (q) => `https://baresearch.org/?q=${encodeURIComponent(q)}` },
  { id: "eg-duckduckgo", label: "DuckDuckGo", tag: "Search", status: "active", inputs: ["query"], url: (q) => `https://duckduckgo.com/?q=${encodeURIComponent(q)}` },
  { id: "eg-startpage", label: "StartPage", tag: "Search", status: "active", inputs: ["query"], url: (q) => `https://startpage.com/do/search?q=${encodeURIComponent(q)}` },
  { id: "eg-qwant", label: "Qwant", tag: "Search", status: "active", inputs: ["query"], url: (q) => `https://www.qwant.com/?q=${encodeURIComponent(q)}` },
  { id: "eg-brave", label: "Brave Search", tag: "Search", status: "active", inputs: ["query"], url: (q) => `https://search.brave.com/search?q=${encodeURIComponent(q)}` },
  { id: "eg-wayback", label: "Wayback Machine", tag: "Search", status: "active", inputs: ["query"], url: (q) => `https://web.archive.org/web/*/${encodeURIComponent(q)}` },
  { id: "eg-ahmia", label: "Ahmia Tor Search", tag: "Search", status: "active", inputs: ["query"], requiresTor: true, url: (q) => `https://ahmia.fi/search/?q=${encodeURIComponent(q)}` },
  { id: "eg-torlink", label: "Tor.link Search", tag: "Search", status: "active", inputs: ["query"], requiresTor: true, url: (q) => `https://tor.link/?q=${encodeURIComponent(q)}` },
  { id: "eg-torch", label: "Torch (.onion)", tag: "Search", status: "active", inputs: ["query"], requiresTor: true, url: (q) => `http://torch4st4l57l2u2vr5wqwvwyueucvnrao4xajqr2klmcmicrv7ccaad.onion/search?query=${encodeURIComponent(q)}&action=search` },
  { id: "eg-tor66", label: "Tor66 (.onion)", tag: "Search", status: "active", inputs: ["query"], requiresTor: true, url: (q) => `http://www.tor66sewebgixwhcqfnp5inzp5x5uohhdy3kvtnyfxc2e5mxiuh34iid.onion/search?q=${encodeURIComponent(q)}` },
  { id: "eg-haystack", label: "Haystack (.onion)", tag: "Search", status: "active", inputs: ["query"], requiresTor: true, url: (q) => `http://haystak5njsmn2hqkewecpaxetahtwhsbsa64jom2k22z5afxhnpxfid.onion/?q=${encodeURIComponent(q)}` },
  { id: "eg-onionland", label: "OnionLand (.onion)", tag: "Search", status: "active", inputs: ["query"], requiresTor: true, url: (q) => `http://3bbad7fauom4d6sgppalyqddsqbf5u5p56b5k5uk2zxsy3d6ey2jobad.onion/search?q=${encodeURIComponent(q)}` },
  { id: "eg-phobos", label: "Phobos (.onion)", tag: "Search", status: "active", inputs: ["query"], requiresTor: true, url: (q) => `http://phobosxilamwcg75xt22id7aywkzol6q6rfl2flipcqoc4e4ahima5id.onion/search?query=${encodeURIComponent(q)}` },
  { id: "eg-deepsearch", label: "DeepSearch (.onion)", tag: "Search", status: "active", inputs: ["query"], requiresTor: true, url: (q) => `http://searchgf7gdtauh7bhnbyed4ivxqmuoat3nm6zfrg3ymkq6mtnpye3ad.onion/search?q=${encodeURIComponent(q)}` },
];

export default engines;
