const financial = [
  { id: "bse-india-dork", label: "BSE India Stock Search (Google)", tag: "Government", status: "active", inputs: ["company"], description: "Lookup listed companies and stock information on Bombay Stock Exchange.", url: (c) => `https://www.google.com/search?q=site%3Abseindia.com+%22${encodeURIComponent(c)}%22` },
  { id: "nse-india-dork", label: "NSE India Search Dork (Google)", tag: "Government", status: "active", inputs: ["company"], description: "Search National Stock Exchange files and announcements for the company.", url: (c) => `https://www.google.com/search?q=site%3Anseindia.com+%22${encodeURIComponent(c)}%22` },
  { id: "sebi-intermediaries-dork", label: "SEBI Registered Intermediaries Dork (Google)", tag: "Government", status: "active", inputs: ["company"], description: "Find SEBI registration logs and regulatory actions for this entity.", url: (c) => `https://www.google.com/search?q=site%3Asebi.gov.in+%22${encodeURIComponent(c)}%22` },
  { id: "mca-filings-dork", label: "MCA Signatories Dork (Google)", tag: "Government", status: "active", inputs: ["company"], description: "Search for registered director signatory lists on the MCA portal.", url: (c) => `https://www.google.com/search?q=site%3Amca.gov.in+%22${encodeURIComponent(c)}%22+signatories` },
  { id: "zauba-import-export-dork", label: "Zauba Import/Export Logs Search (Google)", tag: "Search", status: "active", inputs: ["company"], description: "Search Zauba Corp registry for trade logs and company profiles.", url: (c) => `https://www.google.com/search?q=site%3Azaubacorp.com+%22${encodeURIComponent(c)}%22` },
  { id: "rbi-defaulters-dork", label: "RBI Wilful Defaulters Dork (Google)", tag: "Government", status: "active", inputs: ["company"], description: "Search Reserve Bank of India reports for loan defaulter listings.", url: (c) => `https://www.google.com/search?q=site%3Arbi.org.in+%22${encodeURIComponent(c)}%22+defaulter` },
  { id: "caerin-fraud", label: "CAERIN Corporate Fraud Check", tag: "Search", status: "active", inputs: ["company"], description: "Search CAERIN directory logs for corporate scams and blacklists.", url: (c) => `https://www.google.com/search?q=%22${encodeURIComponent(c)}%22+site%3Acaerin.org` },
  { id: "bse-disclosures-dork", label: "BSE Corporate Announcements Search (Google)", tag: "Government", status: "active", inputs: ["company"], description: "Search BSE corporate filings and disclosures.", url: (c) => `https://www.google.com/search?q=site%3Abseindia.com+%22${encodeURIComponent(c)}%22+announcements` },
  { id: "nse-disclosures-dork", label: "NSE Announcements Dork (Google)", tag: "Government", status: "active", inputs: ["company"], description: "Search Google for corporate filings listed on the NSE portal.", url: (c) => `https://www.google.com/search?q=site%3Anseindia.com+%22${encodeURIComponent(c)}%22+announcements` },
  { id: "google-dork-financial", label: "Corporate Insolvency Google Dork", tag: "Search", status: "active", inputs: ["company"], description: "Search official government domains for default or insolvency listings.", url: (c) => `https://www.google.com/search?q=%22${encodeURIComponent(c)}%22+fraud+OR+solvent+OR+default+site%3Agov.in` }
];

export default financial;
