const government = [
  { id: "uidai", label: "UIDAI Aadhaar Reference Dork (Google)", tag: "Government", status: "active", inputs: ["id"], description: "Search for public index files or references containing this ID on UIDAI.", url: (i) => `https://www.google.com/search?q=site%3Auidai.gov.in+%22${i}%22` },
  { id: "digilocker", label: "DigiLocker Verification Dork (Google)", tag: "Government", status: "active", inputs: ["id"], description: "Search public indexes on digitallocker.gov.in containing this ID.", url: (i) => `https://www.google.com/search?q=site%3Adigilocker.gov.in+%22${i}%22` },
  { id: "voter-id", label: "Voter ID (EPIC) Dork (Google)", tag: "Government", status: "active", inputs: ["id"], description: "Search voters.eci.gov.in index for the target EPIC card number.", url: (i) => `https://www.google.com/search?q=site%3Avoters.eci.gov.in+%22${i}%22` },
  { id: "pan-verify", label: "Income Tax PAN Registry Dork (Google)", tag: "Government", status: "active", inputs: ["id"], description: "Search Income Tax portal indexed documents for the PAN number.", url: (i) => `https://www.google.com/search?q=site%3Aincometax.gov.in+%22${i}%22` },
  { id: "epfo-uan", label: "EPFO UAN Reference Dork (Google)", tag: "Government", status: "active", inputs: ["id"], description: "Search EPFO portal files or PDF indexes for UAN records.", url: (i) => `https://www.google.com/search?q=site%3Aepfindia.gov.in+%22${i}%22` },
  { id: "pm-kisan", label: "PM Kisan Status Dork (Google)", tag: "Government", status: "active", inputs: ["id"], description: "Search PM Kisan beneficiary listings for reference of the ID.", url: (i) => `https://www.google.com/search?q=site%3Apmkisan.gov.in+%22${i}%22` },
  { id: "passport-seva", label: "Passport Seva File Dork (Google)", tag: "Government", status: "active", inputs: ["id"], description: "Search Passport Seva references or applications lists.", url: (i) => `https://www.google.com/search?q=site%3Apassportindia.gov.in+%22${i}%22` },
  { id: "driving-license", label: "Sarathi Driving License Dork (Google)", tag: "Government", status: "active", inputs: ["id"], description: "Search Sarathi DL database indexes for reference of the ID.", url: (i) => `https://www.google.com/search?q=site%3Asarathi.parivahan.gov.in+%22${i}%22` },
  { id: "eshram", label: "e-SHRAM Card Reference Dork (Google)", tag: "Government", status: "active", inputs: ["id"], description: "Search e-SHRAM registry documents for target identification.", url: (i) => `https://www.google.com/search?q=site%3Aeshram.gov.in+%22${i}%22` },
  { id: "msme-udyam", label: "MSME Udyam Registration Dork (Google)", tag: "Government", status: "active", inputs: ["id"], description: "Search MSME portal for registered Udyam numbers or filings.", url: (i) => `https://www.google.com/search?q=site%3Audyamregistration.gov.in+%22${i}%22` },
  { id: "ayushman-bharat", label: "Ayushman Bharat PMJAY Dork (Google)", tag: "Government", status: "active", inputs: ["id"], description: "Search PMJAY beneficiary indexes for reference of the card.", url: (i) => `https://www.google.com/search?q=site%3Apmjay.gov.in+%22${i}%22` },
  { id: "lpg-subsidy", label: "MyLPG Subsidy Status Dork (Google)", tag: "Government", status: "active", inputs: ["id"], description: "Search LPG distributor database indexes for subscriber IDs.", url: (i) => `https://www.google.com/search?q=site%3Amylpg.in+%22${i}%22` },
  { id: "startup-india", label: "Startup India Directory Dork (Google)", tag: "Government", status: "active", inputs: ["id"], description: "Search Startup India database directories for company registration ID.", url: (i) => `https://www.google.com/search?q=site%3Astartupindia.gov.in+%22${i}%22` },
  { id: "dgft-iec", label: "DGFT Import Export Code Dork (Google)", tag: "Government", status: "active", inputs: ["id"], description: "Search DGFT portal records for specific IEC files.", url: (i) => `https://www.google.com/search?q=site%3Adgft.gov.in+%22${i}%22` },
  { id: "rti-online", label: "RTI Online Registry Dork (Google)", tag: "Government", status: "active", inputs: ["id"], description: "Search rtionline.gov.in database index for application status.", url: (i) => `https://www.google.com/search?q=site%3Artionline.gov.in+%22${i}%22` }
];

export default government;
