const instagram = [
  { id: "ig-profile", label: "Instagram Profile Link", tag: "Social", status: "active", inputs: ["username"], description: "Direct link to the user's Instagram profile.", url: (u) => `https://www.instagram.com/${u}/` },
  { id: "ig-channel", label: "Instagram Broadcast Channels", tag: "Social", status: "active", inputs: ["username"], description: "Direct link to the user's public broadcast channels.", url: (u) => `https://www.instagram.com/${u}/channel/` },
  { id: "ig-tagged", label: "Instagram Tagged Photos", tag: "Social", status: "active", inputs: ["username"], description: "View posts in which this user has been tagged.", url: (u) => `https://www.instagram.com/${u}/tagged/` },
  { id: "ig-google-outgoing", label: "Outgoing Username Mentions (Google)", tag: "Search", status: "active", inputs: ["username"], description: "Search Google for posts and web pages mentioning this handle.", url: (u) => `https://www.google.com/search?q=site%3Ainstagram.com+%22${encodeURIComponent(u)}%22` },
  { id: "ig-google-incoming", label: "Incoming @Handle Tags (Google)", tag: "Search", status: "active", inputs: ["username"], description: "Search Google for posts where this user is directly tagged with @username.", url: (u) => `https://www.google.com/search?q=site%3Ainstagram.com+%22%40${encodeURIComponent(u)}%22` },
  { id: "ig-bing", label: "Instagram Username Index (Bing)", tag: "Search", status: "active", inputs: ["username"], description: "Search Bing for any indexed pages mentioning the username.", url: (u) => `https://www.bing.com/search?q=site%3Ainstagram.com+%22${encodeURIComponent(u)}%22` },
  { id: "ig-yandex", label: "Instagram Username Index (Yandex)", tag: "Search", status: "active", inputs: ["username"], description: "Search Yandex for indexed pages matching this username.", url: (u) => `https://yandex.com/search/?text=site%3Ainstagram.com+%22${encodeURIComponent(u)}%22` },
  { id: "ig-twitter-posts", label: "Instagram Posts Shared on X / Twitter", tag: "Search", status: "active", inputs: ["username"], description: "Find tweets containing shared links to this user's Instagram posts.", url: (u) => `https://www.google.com/search?q=site%3Atwitter.com+%22${encodeURIComponent(u)}%22+%22instagram.com%2Fp%22` },
  { id: "ig-dumpor", label: "Dumpor Instagram Viewer & Downloader", tag: "Social", status: "active", inputs: ["username"], description: "Browse posts, stories, and tagged posts anonymously without logging in.", url: (u) => `https://dumpor.com/v/${u}` },
  { id: "ig-toolzu", label: "Toolzu Profile Analyzer", tag: "Social", status: "active", inputs: ["username"], description: "Analyze profile growth, engagement rate, and hashtag statistics.", url: (u) => `https://toolzu.com/profile-analyzer/instagram/?username=${u}` },
  { id: "ig-id-lookup-1", label: "Resolve User ID (InstaFollowers)", tag: "Commercial", status: "active", inputs: ["username"], description: "Find the permanent, numerical user ID associated with this handle.", url: (u) => `https://www.instafollowers.co/find-instagram-user-id` },
  { id: "ig-id-lookup-2", label: "Resolve User ID (CommentPicker)", tag: "Commercial", status: "active", inputs: ["username"], description: "Alternative service to find the permanent numerical Instagram ID.", url: (u) => `https://commentpicker.com/instagram-user-id.php` },
  { id: "ig-followers", label: "Followers GraphQL Endpoint", tag: "Social", status: "active", inputs: ["id"], description: "Direct API query to list the target's followers (requires active session).", url: (i) => `https://www.instagram.com/graphql/query/?query_hash=c76146de99bb02f6415203be841dd25a&variables=${encodeURIComponent(JSON.stringify({id: i, include_reel: true, fetch_mutual: true, first: 50}))}` },
  { id: "ig-following", label: "Following GraphQL Endpoint", tag: "Social", status: "active", inputs: ["id"], description: "Direct API query to list accounts the target follows (requires active session).", url: (i) => `https://www.instagram.com/graphql/query/?query_hash=d04b0a864b4b54837c0d870b0e77e076&variables=${encodeURIComponent(JSON.stringify({id: i, include_reel: true, fetch_mutual: false, first: 50}))}` },
  { id: "ig-user-term", label: "User + Term Search", tag: "Search", status: "active", inputs: ["username", "term"], description: "Find specific keywords or terms mentioned on the user's profile.", url: (u, t) => `https://www.google.com/search?q=site%3Ainstagram.com+%22${encodeURIComponent(u)}%22+%22${encodeURIComponent(t)}%22` },
  { id: "ig-associations", label: "User Associations", tag: "Search", status: "active", inputs: ["username", "username2"], description: "Find pages or posts where both usernames are mentioned together.", url: (u, u2) => `https://www.google.com/search?q=site%3Ainstagram.com+(%22${encodeURIComponent(u)}%22+OR+%22${encodeURIComponent(u2)}%22)` },
  { id: "ig-hashtag", label: "Hashtag Explore Page", tag: "Social", status: "active", inputs: ["hashtag"], description: "Explore public posts tagged with a specific hashtag.", url: (h) => `https://www.instagram.com/explore/tags/${h}/` },
  { id: "ig-terms", label: "Instagram Global Keyword Search", tag: "Search", status: "active", inputs: ["term"], description: "Search Google for any Instagram content containing the keyword.", url: (t) => `https://www.google.com/search?q=site%3Ainstagram.com+${encodeURIComponent(t)}` },
  { id: "ig-dumpor-tag", label: "Dumpor Anonymous Hashtag Viewer", tag: "Social", status: "active", inputs: ["hashtag"], description: "View posts containing this hashtag anonymously on Dumpor.", url: (h) => `https://dumpor.com/t/${h}` },
  { id: "ig-threads", label: "Threads Profile Link", tag: "Social", status: "active", inputs: ["username"], description: "Direct link to the user's Threads.net profile.", url: (u) => `https://www.threads.net/@${u}` },
];

export default instagram;
