const social = [
  { id: "soc-rd-keyword", label: "Reddit Keyword Search", tag: "Social", status: "active", inputs: ["username"], platform: "Reddit", url: (q) => `https://old.reddit.com/search?q=${encodeURIComponent(q)}` },
  { id: "soc-rd-title", label: "Reddit Title Search", tag: "Social", status: "active", inputs: ["username"], platform: "Reddit", url: (q) => `https://old.reddit.com/search?q=title%3A${encodeURIComponent(q)}` },
  { id: "soc-rd-user", label: "Reddit User Profile", tag: "Social", status: "active", inputs: ["username"], platform: "Reddit", url: (u) => `https://old.reddit.com/user/${u}` },
  { id: "soc-rd-submissions", label: "Reddit Submissions List", tag: "Social", status: "active", inputs: ["username"], platform: "Reddit", url: (u) => `https://old.reddit.com/user/${u}/submitted` },
  { id: "soc-rd-comments", label: "Reddit Comments List", tag: "Social", status: "active", inputs: ["username"], platform: "Reddit", url: (u) => `https://old.reddit.com/user/${u}/comments/` },
  { id: "soc-rd-archive", label: "Reddit Wayback Archive", tag: "Search", status: "active", inputs: ["username"], platform: "Reddit", url: (u) => `https://web.archive.org/web/*/https://www.reddit.com/user/${u}` },
  { id: "soc-rd-pullpush-asc", label: "Reddit PullPush History (Asc)", tag: "Search", status: "active", inputs: ["username"], platform: "Reddit", url: (u) => `https://api.pullpush.io/reddit/search/comment/?author=${u}&sort=asc&size=100` },
  { id: "soc-rd-pullpush-desc", label: "Reddit PullPush History (Desc)", tag: "Search", status: "active", inputs: ["username"], platform: "Reddit", url: (u) => `https://api.pullpush.io/reddit/search/comment/?author=${u}&sort=desc&size=100` },
  { id: "soc-rd-domain", label: "Reddit Domain Posts Check", tag: "Search", status: "active", inputs: ["domain"], platform: "Reddit", url: (d) => `https://old.reddit.com/search?q=site%3A${d}` },
  { id: "soc-rd-mention", label: "Reddit Domain Mentions Check", tag: "Search", status: "active", inputs: ["domain"], platform: "Reddit", url: (d) => `https://old.reddit.com/search?q=url%3A${d}` },
  { id: "soc-hn-keyword", label: "HackerNews Algolia Keyword", tag: "Social", status: "active", inputs: ["username"], platform: "HackerNews", url: (q) => `https://hn.algolia.com/?query=${encodeURIComponent(q)}&sort=byDate&prefix&page=0&dateRange=all&type=all` },
  { id: "soc-hn-user", label: "HackerNews User Profile", tag: "Social", status: "active", inputs: ["username"], platform: "HackerNews", url: (u) => `https://news.ycombinator.com/user?id=${u}` },
  { id: "soc-hn-posts", label: "HackerNews User Submissions", tag: "Social", status: "active", inputs: ["username"], platform: "HackerNews", url: (u) => `https://news.ycombinator.com/submitted?id=${u}` },
  { id: "soc-hn-comments", label: "HackerNews User Comments", tag: "Social", status: "active", inputs: ["username"], platform: "HackerNews", url: (u) => `https://news.ycombinator.com/threads?id=${u}` },
  { id: "soc-4chan-search", label: "4Chan Board Search", tag: "Social", status: "active", inputs: ["username"], platform: "4Chan", url: (q) => `http://4chansearch.com/?q=${encodeURIComponent(q)}&s=4` },
  { id: "soc-4plebs-search", label: "4Plebs Archive Search", tag: "Social", status: "active", inputs: ["username"], platform: "4Chan", url: (q) => `https://archive.4plebs.org/_/search/text/${encodeURIComponent(q)}/order/asc/` },
  { id: "soc-tt-profile", label: "TikTok User Profile", tag: "Social", status: "active", inputs: ["username"], platform: "TikTok", url: (u) => `https://www.tiktok.com/@${u}` },
  { id: "soc-tt-search-user", label: "TikTok User Search Directory", tag: "Social", status: "active", inputs: ["username"], platform: "TikTok", url: (u) => `https://www.tiktok.com/search/user?q=${encodeURIComponent(u)}` },
  { id: "soc-tt-tag", label: "TikTok Tag Explorer", tag: "Social", status: "active", inputs: ["username"], platform: "TikTok", url: (t) => `https://www.tiktok.com/tag/${t}` },
  { id: "soc-tt-search-term", label: "TikTok Video Keyword Search", tag: "Social", status: "active", inputs: ["username"], platform: "TikTok", url: (t) => `https://www.tiktok.com/search?q=${encodeURIComponent(t)}` },
  { id: "soc-tt-analytics", label: "TikTok Exolyt Analytics", tag: "Social", status: "active", inputs: ["username"], platform: "TikTok", url: (u) => `https://exolyt.com/user/${u}` },
  { id: "soc-meetup-member", label: "Meetup Member Indexing", tag: "Social", status: "active", inputs: ["username"], platform: "Meetup", url: (u) => `https://www.google.com/search?q=site:meetup.com+${encodeURIComponent(u)}` },
  { id: "soc-meetup-events", label: "Meetup Events Indexing", tag: "Social", status: "active", inputs: ["username"], platform: "Meetup", url: (k) => `https://www.google.com/search?q=site:meetup.com+inurl:events+${encodeURIComponent(k)}` },
  { id: "soc-ebay-usr", label: "Ebay User Storefront", tag: "Social", status: "active", inputs: ["username"], platform: "Ebay", url: (u) => `https://www.ebay.com/usr/${u}` },
  { id: "soc-ebay-feedback", label: "Ebay User Feedback Log", tag: "Social", status: "active", inputs: ["username"], platform: "Ebay", url: (u) => `https://feedback.ebay.com/ws/eBayISAPI.dll?ViewFeedback2&userid=${u}` },
  { id: "soc-pinterest-usr", label: "Pinterest Profile Page", tag: "Social", status: "active", inputs: ["username"], platform: "Pinterest", url: (u) => `https://www.pinterest.com/${u}` },
  { id: "soc-pinterest-created", label: "Pinterest Created Pins Tab", tag: "Social", status: "active", inputs: ["username"], platform: "Pinterest", url: (u) => `https://www.pinterest.com/${u}/_created/` },
  { id: "soc-pinterest-saved", label: "Pinterest Saved Pins Tab", tag: "Social", status: "active", inputs: ["username"], platform: "Pinterest", url: (u) => `https://www.pinterest.com/${u}/_saved/` },
  { id: "soc-discord-disboard", label: "Discord Server Finder (Disboard)", tag: "Social", status: "active", inputs: ["username"], platform: "Discord", url: (k) => `https://disboard.org/search?keyword=${encodeURIComponent(k)}` },
  { id: "soc-discord-me", label: "Discord.me Guild Finder", tag: "Social", status: "active", inputs: ["username"], platform: "Discord", url: (k) => `https://discord.me/servers?search=${encodeURIComponent(k)}` },
  { id: "soc-discord-servers", label: "DiscordServers Guild Finder", tag: "Social", status: "active", inputs: ["username"], platform: "Discord", url: (k) => `https://discordservers.com/search/${encodeURIComponent(k)}` },
  { id: "soc-parler-usr", label: "Parler Public Profile", tag: "Social", status: "active", inputs: ["username"], platform: "Parler", url: (u) => `https://app.parler.com/${u}` },
  { id: "soc-gab-usr", label: "Gab Public Profile", tag: "Social", status: "active", inputs: ["username"], platform: "Gab", url: (u) => `https://gab.com/${u}` },
  { id: "soc-gettr-usr", label: "Gettr Public Profile", tag: "Social", status: "active", inputs: ["username"], platform: "Gettr", url: (u) => `https://www.gettr.com/user/${u}` },
  { id: "soc-mastodon-search", label: "Mastodon Accounts Search API", tag: "Social", status: "active", inputs: ["username"], platform: "Mastodon", url: (u) => `https://mastodon.social/api/v2/search?q=${encodeURIComponent(u)}&limit=40&type=accounts` },
  { id: "soc-tg-channel", label: "Telegram Channel Redirect", tag: "Social", status: "active", inputs: ["username"], platform: "Telegram", url: (u) => `https://t.me/${u}` },
  { id: "soc-tg-preview", label: "Telegram Web Channel Preview", tag: "Social", status: "active", inputs: ["username"], platform: "Telegram", url: (u) => `https://telegram.me/s/${u}` },
  { id: "soc-tg-search-group", label: "Telegram Group Finder Index", tag: "Social", status: "active", inputs: ["username"], platform: "Telegram", url: (k) => `https://www.telegram-group.com/en?s=${encodeURIComponent(k)}` },
  { id: "soc-tg-search-chan", label: "Telegram Channel Finder Index", tag: "Social", status: "active", inputs: ["username"], platform: "Telegram", url: (k) => `https://telegramchannels.me/search?type=all&search=${encodeURIComponent(k)}` }
];

export default social;
