const twitter = [
  { id: "tw-profile", label: "Twitter Profile", tag: "Social", status: "active", inputs: ["username"], url: (u) => `https://twitter.com/${u}` },
  { id: "tw-outgoing", label: "Outgoing Tweets", tag: "Social", status: "active", inputs: ["username"], url: (u) => `https://twitter.com/search?q=from%3A${u}&f=live` },
  { id: "tw-incoming", label: "Incoming Tweets", tag: "Social", status: "active", inputs: ["username"], url: (u) => `https://twitter.com/search?q=to%3A${u}&f=live` },
  { id: "tw-replies", label: "Only Replies", tag: "Social", status: "active", inputs: ["username"], url: (u) => `https://twitter.com/search?q=from%3A${u}%20filter%3Areplies&src=typed_query&f=live` },
  { id: "tw-noreplies", label: "No Replies", tag: "Social", status: "active", inputs: ["username"], url: (u) => `https://twitter.com/search?q=from%3A${u}%20-filter%3Areplies&src=typed_query&f=live` },
  { id: "tw-media", label: "Media Tweets", tag: "Social", status: "active", inputs: ["username"], url: (u) => `https://twitter.com/${u}/media/` },
  { id: "tw-highlights", label: "Highlighted Tweets", tag: "Social", status: "active", inputs: ["username"], url: (u) => `https://twitter.com/${u}/highlights/` },
  { id: "tw-lists-created", label: "Lists Created", tag: "Social", status: "active", inputs: ["username"], url: (u) => `https://twitter.com/${u}/lists/` },
  { id: "tw-lists-included", label: "Lists Included", tag: "Social", status: "active", inputs: ["username"], url: (u) => `https://twitter.com/${u}/lists/memberships` },
  { id: "tw-topics", label: "Topics Followed", tag: "Social", status: "active", inputs: ["username"], url: (u) => `https://twitter.com/${u}/topics` },
  { id: "tw-links", label: "Tweets with Links", tag: "Social", status: "active", inputs: ["username"], url: (u) => `https://twitter.com/search?q=from%3A${u}%20filter%3Alinks&src=typed_query&f=live` },
  { id: "tw-followers", label: "Followers", tag: "Social", status: "active", inputs: ["username"], url: (u) => `https://twitter.com/${u}/followers` },
  { id: "tw-following", label: "Following", tag: "Social", status: "active", inputs: ["username"], url: (u) => `https://twitter.com/${u}/following` },
  { id: "tw-out-year", label: "Outgoing by Year", tag: "Search", status: "active", inputs: ["username", "year"], url: (u, y) => `https://twitter.com/search?q=from%3A${u}%20since%3A${y}-01-01%20until%3A${y}-12-31&src=typd&f=live` },
  { id: "tw-in-year", label: "Incoming by Year", tag: "Search", status: "active", inputs: ["username", "year"], url: (u, y) => `https://twitter.com/search?q=to%3A${u}%20since%3A${y}-01-01%20until%3A${y}-12-31&src=typd&f=live` },
  { id: "tw-media-year", label: "Media by Year", tag: "Search", status: "active", inputs: ["username", "year"], url: (u, y) => `https://twitter.com/search?q=from%3A${u}%20since%3A${y}-01-01%20until%3A${y}-12-31%20filter%3Amedia&src=typd&f=live` },
  { id: "tw-term-year", label: "Term by Year", tag: "Search", status: "active", inputs: ["term", "year"], url: (t, y) => `https://twitter.com/search?q=${encodeURIComponent(t)}%20since%3A${y}-01-01%20until%3A${y}-12-31&src=typd&f=live` },
  { id: "tw-xcancel-profile", label: "XCancel Profile", tag: "Social", status: "active", inputs: ["username"], url: (u) => `https://xcancel.com/${u}` },
  { id: "tw-xcancel-out", label: "XCancel Outgoing", tag: "Social", status: "active", inputs: ["username"], url: (u) => `https://xcancel.com/search?q=from%3A${u}&f=live` },
  { id: "tw-xcancel-in", label: "XCancel Incoming", tag: "Social", status: "active", inputs: ["username"], url: (u) => `https://xcancel.com/search?q=to%3A${u}&f=live` },
  { id: "tw-google-archive", label: "Google Archive", tag: "Search", status: "active", inputs: ["username"], url: (u) => `https://www.google.com/search?q=site%3Atwitter.com%2F${u}` },
  { id: "tw-google-tweets", label: "Google Tweets Status", tag: "Search", status: "active", inputs: ["username"], url: (u) => `https://www.google.com/search?q=site%3Atwitter.com%2F${u}%2Fstatus%2F` },
  { id: "tw-bing-archive", label: "Bing Archive", tag: "Search", status: "active", inputs: ["username"], url: (u) => `https://www.bing.com/search?q=twitter.com%2F${u}` },
  { id: "tw-yandex-archive", label: "Yandex Archive", tag: "Search", status: "active", inputs: ["username"], url: (u) => `https://www.yandex.com/search/?text=https%3A%2F%2Ftwitter.com%2F${u}` },
  { id: "tw-wayback", label: "Wayback Machine", tag: "Search", status: "active", inputs: ["username"], url: (u) => `https://web.archive.org/web/*/twitter.com/${u}` },
  { id: "tw-history-user", label: "Historical Profile", tag: "Search", status: "active", inputs: ["username"], url: (u) => `https://api.memory.lol/v1/tw/${u}` },
  { id: "tw-history-id", label: "Historical User ID", tag: "Search", status: "active", inputs: ["id"], url: (i) => `https://api.memory.lol/v1/tw/id/${i}` },
  { id: "tw-audit", label: "Twitter Audit", tag: "Social", status: "active", inputs: ["username"], url: (u) => `https://www.twitteraudit.com/${u}` },
  { id: "tw-profile-search", label: "Profile Search", tag: "Search", status: "active", inputs: ["name"], url: (n) => `https://twitter.com/search?q=${encodeURIComponent(n)}&f=user` },
  { id: "tw-list-view", label: "List View Check", tag: "Social", status: "active", inputs: ["listid"], url: (l) => `https://twitter.com/i/lists/${l}` },
  { id: "tw-list-members", label: "List Members Check", tag: "Social", status: "active", inputs: ["listid"], url: (l) => `https://twitter.com/i/lists/${l}/members` },
  { id: "tw-list-followers", label: "List Followers Check", tag: "Social", status: "active", inputs: ["listid"], url: (l) => `https://twitter.com/i/lists/${l}/followers` },
];

export default twitter;
