const usernames = [
  { id: "us-google", label: "Google Username Index", tag: "Search", status: "active", inputs: ["username"], url: (u) => `https://www.google.com/search?q=%22${encodeURIComponent(u)}%22` },
  { id: "us-bing", label: "Bing Username Index", tag: "Search", status: "active", inputs: ["username"], url: (u) => `https://www.bing.com/search?q=%22${encodeURIComponent(u)}%22` },
  { id: "us-yandex", label: "Yandex Username Index", tag: "Search", status: "active", inputs: ["username"], url: (u) => `https://yandex.com/search/?text=%22${encodeURIComponent(u)}%22` },
  { id: "us-idcrawl", label: "ID Crawl Checker", tag: "Social", status: "active", inputs: ["username"], url: (u) => `https://www.idcrawl.com/u/${u}` },
  { id: "us-instant", label: "InstantUsername", tag: "Social", status: "active", inputs: ["username"], url: (u) => `https://instantusername.com/?q=${u}` },
  { id: "us-namechecker", label: "NameChecker", tag: "Social", status: "active", inputs: ["username"], url: (u) => `https://www.namechecker.org/#${u}` },
  { id: "us-namechk", label: "NameChck", tag: "Social", status: "active", inputs: ["username"], url: (u) => `https://namechk.com/namechk-plugin-search-results/?n=${u}` },
  { id: "us-namevine", label: "NameVine", tag: "Social", status: "active", inputs: ["username"], url: (u) => `https://namevine.com/#/${u}` },
  { id: "us-profilediscover", label: "ProfileDiscover", tag: "Social", status: "active", inputs: ["username"], url: (u) => `https://profilediscover.com/${u}` },
  { id: "us-socialsearcher", label: "SocialSearcher", tag: "Social", status: "active", inputs: ["username"], url: (u) => `https://www.social-searcher.com/search-users/?ntw=&q6=${u}` },
  { id: "us-checkistan", label: "Checkistan", tag: "Social", status: "active", inputs: ["username"], url: (u) => `https://usernamechecker.checkistan.com/#${u}` },
  { id: "us-usersearch-normal", label: "UserSearch Normal", tag: "Social", status: "active", inputs: ["username"], url: (u) => `https://usersearch.org/results_normal.php?URL_username=${u}` },
  { id: "us-usersearch-adv", label: "UserSearch Advanced", tag: "Social", status: "active", inputs: ["username"], url: (u) => `https://usersearch.org/results_advanced.php?URL_username=${u}` },
  { id: "us-usersearch-dating", label: "UserSearch Dating", tag: "Social", status: "active", inputs: ["username"], url: (u) => `https://usersearch.org/results_dating.php?URL_username=${u}` },
  { id: "us-usersearch-forums", label: "UserSearch Forums", tag: "Social", status: "active", inputs: ["username"], url: (u) => `https://usersearch.org/results_forums.php?URL_username=${u}` },
  { id: "us-usersearch-crypto", label: "UserSearch Crypto", tag: "Social", status: "active", inputs: ["username"], url: (u) => `https://usersearch.org/results_crypto.php?URL_username=${u}` },
  { id: "us-dehashed", label: "Dehashed Username", tag: "Search", status: "active", inputs: ["username"], url: (u) => `https://dehashed.com/search?query=%22${u}%22` },
  { id: "us-psbdmp", label: "PSBDMP Search", tag: "Search", status: "active", inputs: ["username"], url: (u) => `https://psbdmp.ws/api/search/${u}` },
  { id: "us-gravatar", label: "Gravatar", tag: "Social", status: "active", inputs: ["username"], url: (u) => `https://en.gravatar.com/${u}` },
  { id: "us-linktree", label: "LinkTree Profile", tag: "Social", status: "active", inputs: ["username"], url: (u) => `https://linktr.ee/${u}` },
  { id: "us-tinder", label: "Tinder Profile", tag: "Social", status: "active", inputs: ["username"], url: (u) => `https://tinder.com/@${u}` },
  { id: "us-tumblr", label: "Tumblr Blog", tag: "Social", status: "active", inputs: ["username"], url: (u) => `https://${u}.tumblr.com` },
  { id: "us-snapchat", label: "Snapchat Profile", tag: "Social", status: "active", inputs: ["username"], url: (u) => `https://www.snapchat.com/s/${u}` },
  { id: "us-medium", label: "Medium Blog", tag: "Social", status: "active", inputs: ["username"], url: (u) => `https://medium.com/@${u}` },
  { id: "us-youtube", label: "YouTube Profile", tag: "Social", status: "active", inputs: ["username"], url: (u) => `https://youtube.com/${u}` },
  { id: "us-reddit", label: "Reddit User Profile", tag: "Social", status: "active", inputs: ["username"], url: (u) => `https://www.reddit.com/user/${u}` },
];

export default usernames;
